### ISSUE TITLE
Bindings error io.js 1.0.3

### ISSUE THREAD

**Issue by DominicBoettger** [TooTallNate/node-bindings#16]
Hello,

i tried to use bcrypt with io.js today and got this error:

node_modules/bcrypt/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)

Do you already know this issue?

Best regards
Dominic

**Comment by xhallix** [comment]
Same here for latest iojs v1.1.0 on linux mint.

**Comment by ximex** [comment]
same here. 0.10.33 but works with 0.12.0

**Comment by TooTallNate** [comment]
Not an issue with this module. Did you try making an issue on the `bcrypt` issue tracker first?
