### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by shotlom** [TooTallNate/node-bindings#18]
I'm using [level](https://github.com/Level/level) in an electron app, and electron is complaining about [L10](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L10). 

It seems that this has been deprecated?

**Comment by n-riesco** [comment]
@shotlom I've submitted PR #20 to fix this warning but I haven't tested it with electron.

**Comment by ralphtheninja** [comment]
@shotlom Which version of node/electron are you running?

**Comment by shotlom** [comment]
node v0.12.7 (npm v2.11.3)

electron v0.31.1

On Thu, Nov 19, 2015 at 11:18 AM, Lars-Magnus Skog <notifications@github.com
> wrote:

> @shotlom <https://github.com/shotlom> Which version of node/electron are
> you running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TooTallNate/node-bindings/issues/18#issuecomment-157915786>
> .
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by StephenClement** [comment]
I am having the same issue with Meteor 1.4. Based on some looking around it looks like fs.existsSync and path.existsSync have both been deprecated.
