### ISSUE TITLE
Support node v4.1.1

### ISSUE THREAD

**Issue by willwhitney** [TooTallNate/node-bindings#19]
Per https://github.com/willwhitney/hydrogen/issues/135, this package seems to cause an error on node v4.1.1. Hydrogen (an Atom package) depends on https://github.com/JustinTulloss/zeromq.node, which depends on this package.

If this isn't related to `node-bindings`, please let me know!

**Comment by n-riesco** [comment]
Also see https://github.com/atom/atom/issues/9660

**Comment by n-riesco** [comment]
@willwhitney I think this issue should be closed here (since it's already fixed in Atom).

**Comment by willwhitney** [comment]
Yup!
