### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by sanjay-ng** [TooTallNate/node-bindings#33]
Hi, 
I'm getting the following error: "Error: Module version mismatch. Expected 48, got 46."

Tried re-installing node, deleted node_modules and cleared cached, still didn't work. Please let me know what can I do to solve it? Thank you in advance.

Tried these and still no solution:
https://github.com/audreyt/node-webworker-threads/issues/109
https://github.com/Level/level/issues/39

![image](https://cloud.githubusercontent.com/assets/25607348/23897693/25dc0c0e-08d4-11e7-8847-a7495c0f40a3.png)

**Comment by sanjay-ng** [comment]
Finally able to solve the issue. Installed **Node.js v4.8.0** and solved the issue.

**Comment by TooTallNate** [comment]
You need to re-compile (most likely just re-install from npm and it will be re-compiled automatically) the module.

**Comment by sanjay-ng** [comment]
I did try to re-install from npm and but had no luck. After installing node 4.8.0, it worked.

**Comment by flaviolsousa** [comment]
it worked for me now ... on my computer I have the version 6.12 node and on the server was version 4.1 ... after upgrading the node on the server to version 6.10, the problem has disappeared. Thank you all!

**Comment by flaviolsousa** [comment]
it worked for me now ... on my computer I have the version 6.12 node and on the server was version 4.1 ... after upgrading the node on the server to version 6.10, the problem has disappeared. Thank you all!
