### ISSUE TITLE
Uncaught Type error - exists is not a function. Integrating C library into node js

### ISSUE THREAD

**Issue by rakeshgn31** [TooTallNate/node-bindings#34]
I am integrating a C library into a chrome app codebase that uses AngularJS and NodeJS as well. I am using node-ffi for integration. Though fs package is used at many places in the codebase, it throws error only at bindings.js code when I launch my application. I think it is trying to identify the ref and ffi modules related to my angular service that uses them. I did replace your fix in bindings.js file as below

  `, exists = ((fs.accessSync && function (path) { try { fs.accessSync(path); } catch (e) { return false; } return true; }) || fs.existsSync || path.existsSync)`

Still I am getting the same error. Removing my ffi integration runs the chrome app well. @TooTallNate  Could you please suggest me on this issue? It has been stopping my work from long time.

**Comment by rakeshgn31** [comment]
This issue gets solved by removing the above line completely and replacing the exists(join code with fs.accessSync(join(dir, ........ code within a try...catch.

**Comment by rakeshgn31** [comment]
@TooTallNate Any suggestion on this issue?

**Comment by alis-sol** [comment]
Hello, I have this problem too. I'm trying to use node-rdkafka which depends on node-bindings. Is there any solution?

**Comment by EsoterikStare** [comment]
Also having this issue on a Raspberry Pi running Node 8.x, bindings@1.2.1. Tried the fix mentioned in #20, which OP mentions with no luck. Any help?

**Comment by alis-sol** [comment]
I found out that both require('fs') and require('path') are returning undefined, and that's why exists remains undefined too (thus, 'not a function'). Maybe it has something to do with our environment and how things are set up? I'm using angular 4 and angular cli 1.2.3.

**Comment by TooTallNate** [comment]
Can you try v1.3.0 please?

**Comment by alis-sol** [comment]
@TooTallNate, thank you very much for looking into this. V1.3.0 still gives the same error because there were no changes in the code, the last commit only removed a trailing space. Maybe you did a mistake when committing?

**Comment by TooTallNate** [comment]
Are you sure? This should be the diff between v1.2.1 and 1.3.0: https://github.com/TooTallNate/node-bindings/compare/v1.2.1...v1.3.0

**Comment by rakeshgn31** [comment]
@alis-sol @EsoterikStare @TooTallNate  Hi People... Sorry for being late. I was not successful in solving it with direct integration. I had to run NodeJS server application and make a REST API call from AngularJS. I kinda worked around the problem.

**Comment by alis-sol** [comment]
@TooTallNate sorry for not being clear. I was already using commit 228973f because I previously had the problem related in issue #20. I meant that the only commit after that just removed a whitespace.

Besides "exists is not a function", I also get these warnings:

WARNING in ./~/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression

I found out that exists is undefined because require('fs') and require('path') both return undefined, but didn't throw any errors. I'm using angular 4 with angular cli 1.2.3. Maybe I'm doing something wrong / incompatible?

@rakeshgn31 thanks for taking the time to reply.

**Comment by alis-sol** [comment]
@TooTallNate @EsoterikStare any news?

**Comment by TooTallNate** [comment]
@alis-sol I'm sorry to day, but this is an issue with your build setup/configuration. This module is intended to work with Node.js directly and if your build tooling is complaining then you kind of need to figure it out from there. There's not really anything I can do in this module to help.

@rakeshgn31 As for the original issue, if you're trying run this C library in the web browser, you might have better luck [compiling the C library with Emscripten](https://github.com/kripken/emscripten), though I warn that it's not the most user-friendly tool to get working nicely.

Please open a new issue for any further discussion. Thanks!
