### ISSUE TITLE
is it working with webpack?

### ISSUE THREAD

**Issue by sylhero** [TooTallNate/node-bindings#38]
I got the following message while building with webpack:
`WARNING in ./~/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ffi/~/bindings/bindings.js
82:28-46 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ffi/~/bindings/bindings.js
82:49-59 Critical dependency: the request of a dependency is an expression
`

node: 7.7.4
npm: 4.1.2
webpack: 2.2

**Comment by TooTallNate** [comment]
Sorry, but no this module does not work with webpack because it utilizes [a dynamic require call](https://github.com/TooTallNate/node-bindings/blob/58141c6ce00b2f7690d7115e6635fdd5739b7fd0/bindings.js#L81).

**Comment by jxblue** [comment]
@TooTallNate Is there any way to suppress the warning?
