### ISSUE TITLE
Cannot read property 'indexOf' of undefined  at Function.getFileName

### ISSUE THREAD

**Issue by dodoto** [TooTallNate/node-bindings#76]
after I reinstalled node_modules, when I launch the project, I got this error :
> Uncaught TypeError: Cannot read property 'indexOf' of undefined
>     at Function.getFileName (D:\my-project\node_modules\bindings\bindings.js:179:16)
>     at bindings (D:\my-project\node_modules\bindings\bindings.js:82:48)
>     at getRealmConstructor (D:\my-project\node_modules\realm\lib\index.js:34:37)
>     at Object.<anonymous> (D:\my-project\node_modules\realm\lib\index.js:59:26)
>     at Object.<anonymous> (D:\my-project\node_modules\realm\lib\index.js:68:3)
>     at Module._compile (internal/modules/cjs/loader.js:1078:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
>     at Module.load (internal/modules/cjs/loader.js:935:32)
>     at Module._load (internal/modules/cjs/loader.js:776:14)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)

**Comment by faebut** [comment]
I get the same error and could not find any solution. How did you solve this?

**Comment by dodoto** [comment]
> I get the same error and could not find any solution. How did you solve this?
Actually I don't konw solution of this error. This error happend when I use realm.js. It worked well in the beigining. But after several days, I got the error. So  I just reset my code and reinstall, it works well.

**Comment by xiaoxiaoqing-win** [comment]
> > I get the same error and could not find any solution. How did you solve this?
> > Actually I don't konw solution of this error. This error happend when I use realm.js. It worked well in the beigining. But after several days, I got the error. So  I just reset my code and reinstall, it works well.

how to reset code or reinstall?

**Comment by dodoto** [comment]
> > > I get the same error and could not find any solution. How did you solve this?
> > > Actually I don't konw solution of this error. This error happend when I use realm.js. It worked well in the beigining. But after several days, I got the error. So  I just reset my code and reinstall, it works well.
> 
> how to reset code or reinstall?

use git reset --hard
